import { useEffect, useState } from 'react';
import { Line } from 'react-chartjs-2';
import { Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend } from 'chart.js';
import { TrendingUp, AlertTriangle, ShieldAlert, FileText, RefreshCw, ExternalLink } from 'lucide-react';

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend);

interface IntelData {
  meta: { last_updated: string; source: string };
  market_index: { date: string; value: number }[];
  spot_prices: Record<string, number>;
  tariffs: { target: string; rate: string; status: string; impact: string }[];
  alert: string;
}

function App() {
  const [data, setData] = useState<IntelData | null>(null);
  const [loading, setLoading] = useState(true);
  const [lobbyTarget, setLobbyTarget] = useState('USTR');
  const [brief, setBrief] = useState('');

  useEffect(() => {
    // Looks for the data file generated by Python
    fetch('./data.json')
      .then(res => res.json())
      .then(setData)
      .catch(err => console.error("Pipeline warming up...", err))
      .finally(() => setLoading(false));
  }, []);

  const generateBrief = () => {
    if (!data) return;
    const date = new Date().toLocaleDateString();
    const oakPrice = data.spot_prices['Red Oak (4/4 Select)'] || 'N/A';
    
    let text = `TO: ${lobbyTarget}\nFROM: PRESIDENT, KRETZ LUMBER\nDATE: ${date}\nSUBJECT: URGENT TRADE IMPACT REPORT\n\n`;
    
    if (lobbyTarget === 'USTR') {
      text += `Ambassador,\n\nOur real-time market data indicates a critical depression in Wisconsin Red Oak prices ($${oakPrice}/MBF), directly correlated to the Section 301 retaliatory tariffs. We are losing market share to Russian Birch. We request an immediate exclusion for HTS 4407.91.`;
    } else {
      text += `Senator,\n\nInput costs for our Antigo operations are rising while export markets remain capped by tariffs. We need your support for the Hardwood Access Program in the upcoming Farm Bill to protect forestry jobs in Langlade County.`;
    }
    setBrief(text);
  };

  if (loading) return <div className="min-h-screen bg-slate-950 flex items-center justify-center text-green-500 font-mono">INITIALIZING KRETZ COMMAND...</div>;

  return (
    <div className="min-h-screen bg-slate-950 text-slate-200 font-sans p-4 md:p-8">
      <header className="max-w-7xl mx-auto mb-8 border-b border-red-900/50 pb-4 flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-white">KRETZ <span className="text-red-600">COMMAND</span></h1>
          <p className="text-xs text-slate-500 tracking-widest uppercase mt-1">Strategic Hardwood Intelligence | Antigo, WI</p>
        </div>
        <div className="text-right hidden md:block">
          <div className="flex items-center justify-end gap-2 text-green-500 text-xs font-bold">
            <span className="animate-pulse">●</span> LIVE FEED ACTIVE
          </div>
          <p className="text-xs text-slate-600 font-mono mt-1">{data?.meta.last_updated}</p>
        </div>
      </header>

      <main className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* COL 1: MARKET STATUS */}
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-red-950/30 border-l-4 border-red-600 p-4 flex gap-4 items-start rounded-r-lg">
            <AlertTriangle className="text-red-500 shrink-0" />
            <div>
              <h3 className="font-bold text-red-400 text-sm">PRESIDENT'S ALERT</h3>
              <p className="text-sm text-red-200/80 mt-1">{data?.alert}</p>
            </div>
          </div>

          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-2xl">
            <div className="flex justify-between items-center mb-6">
              <h2 className="text-lg font-semibold flex items-center gap-2">
                <TrendingUp className="text-blue-500" size={20} />
                Market History (FRED WPU081)
              </h2>
            </div>
            <div className="h-[300px]">
              <Line 
                data={{
                  labels: data?.market_index.map(d => d.date),
                  datasets: [{
                    label: 'Hardwood PPI Index',
                    data: data?.market_index.map(d => d.value),
                    borderColor: '#3b82f6',
                    backgroundColor: 'rgba(59, 130, 246, 0.1)',
                    fill: true,
                    tension: 0.4
                  }]
                }}
                options={{
                  responsive: true,
                  maintainAspectRatio: false,
                  scales: { y: { grid: { color: '#1e293b' } }, x: { grid: { color: '#1e293b' } } }
                }}
              />
            </div>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {Object.entries(data?.spot_prices || {}).map(([species, price]) => (
              <div key={species} className="bg-slate-900 border border-slate-800 p-4 rounded-lg text-center">
                <p className="text-xs text-slate-500 uppercase font-bold tracking-wider">{species}</p>
                <p className="text-2xl font-bold text-white mt-1">${price}</p>
                <p className="text-[10px] text-slate-600">PER MBF</p>
              </div>
            ))}
          </div>
        </div>

        {/* COL 2: ACTION CENTER */}
        <div className="space-y-6">
          
          {/* LINK TO TIMBER TOOL */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
             <h2 className="text-lg font-semibold flex items-center gap-2 mb-4">
              <ExternalLink className="text-emerald-500" size={20} />
              Valuation Tools
            </h2>
            <a href="./market.html" className="block w-full bg-emerald-900/40 hover:bg-emerald-800/60 border border-emerald-700/50 text-emerald-100 font-bold py-4 rounded-lg text-center transition-all">
              🌲 OPEN TIMBER CALCULATOR
            </a>
          </div>

          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
            <h2 className="text-lg font-semibold flex items-center gap-2 mb-4">
              <ShieldAlert className="text-amber-500" size={20} />
              Tariff Radar
            </h2>
            <div className="space-y-3">
              {data?.tariffs.map((t) => (
                <div key={t.target} className="bg-slate-950 p-3 rounded border border-slate-800 flex justify-between items-center">
                  <div>
                    <div className="font-bold text-sm text-slate-200">{t.target}</div>
                    <div className="text-xs text-slate-500">{t.rate}</div>
                  </div>
                  <span className={`text-xs font-bold px-2 py-1 rounded ${
                    t.status === 'CRITICAL' ? 'bg-red-900/50 text-red-400' :
                    t.status === 'WARNING' ? 'bg-amber-900/50 text-amber-400' :
                    'bg-green-900/50 text-green-400'
                  }`}>{t.status}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
            <h2 className="text-lg font-semibold flex items-center gap-2 mb-4">
              <FileText className="text-purple-500" size={20} />
              Lobbying Generator
            </h2>
            <div className="space-y-3">
              <select 
                className="w-full bg-slate-950 border border-slate-700 rounded p-2 text-sm text-slate-200"
                value={lobbyTarget}
                onChange={(e) => setLobbyTarget(e.target.value)}
              >
                <option value="USTR">USTR (Ambassador)</option>
                <option value="SENATE">US Senate (WI)</option>
              </select>
              <button 
                onClick={generateBrief}
                className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 rounded text-sm flex items-center justify-center gap-2"
              >
                <RefreshCw size={14} /> GENERATE BRIEF
              </button>
              <textarea 
                readOnly
                value={brief}
                placeholder="Brief will appear here..."
                className="w-full h-40 bg-slate-950 border border-slate-700 rounded p-3 text-xs font-mono text-green-400 resize-none focus:outline-none"
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

export default App;
